    @Test
    public void testSynchronizeWithArithmeticException() throws Exception {
        TmfTimestamp bigBang   = new TmfTimestamp(TmfTimestamp.BigBang);
        TmfTimestamp bigCrunch = new TmfTimestamp(TmfTimestamp.BigCrunch);

        try {
            bigCrunch.synchronize(bigBang.getValue(), bigBang.getScale());
            fail("Exception not thrown");
        } catch (ArithmeticException e) {          
        }
    }

