    @Test
    public void testWrappedAssignment_2_Bug277624() throws Exception {
        assertIndenterResult(
                "{\n" +
                "a = 0;\n" +
                "x = 2 +\n" +
                "2 +\n" +
                "2;",

                "{\n" +
                "\ta = 0;\n" +
                "\tx = 2 +\n" +
                "\t\t\t2 +\n" +
                "\t\t\t2;");
    }

